# (PART) Vorbereitung {-}

# Was ist R

R ist eine Programmiersprache, und ja, das klingt abschreckend.  
Für uns heißt das in erster Linie Folgendes:

- Die Lernkurve ist etwas steil, flacht dann aber schnell ab. Versprochen.
- Wir können prinzipiell _alles_ damit machen, wenn wir erstmal rausgefunden haben wie's geht.

## Wieso nicht einfach SPSS?

SPSS ist viel.  
SPSS kann viel.  
SPSS kostet unsäglich viel.  
SPSS nimmt euch das Denken ab — im guten wie im schlechten Sinn.  

Wenn ihr SPSS bedienen könnt, ihr wisst was ihr tut und entweder ihr oder eure ArbeitgeberIn tief in die Tasche gegriffen haben um eine Lizenz bereitzustellen, dann ist das schön und gut, und ihr könnt den Knopf mit *"Mach mal Statistik"* drücken und dann kommen da PDFs raus wo Statistik drinsteht.  
Schön.

Möglicherweise habt ihr aber nicht die finanziellen Ressourcen für SPSS.  
Möglicherweise braucht ihr mehr Flexibilität.  
Vielleicht funktioniert SPSS für euch nur mittels einer Remotedesktop-Verbindung (\*hust hust\*), das heißt sobald ihr irgendwo ohne schnelle Verbindung seid, könnt ihr nicht mehr arbeiten.  
So sicher wie der Tod und Steuern müsst ihr auch irgendwann ein Expra durchführen, die erhobenen Daten auswerten und darstellen. Solltet ihr das mit SPSS machen, dürft ihr keine der Grafiken oder Tabellen benutzen (außer ihr verzichtet freiwillig auf eine gute Note). Das gleiche gilt in schwächerer Gewichtung für euer Differentielle Projekt und natürlich ggf. in stärkerer Gewichtung für eure Bachelorarbeit.

Vielleicht gefällt euch aber auch nur, dass ihr mit R interaktiv und schnell[^schnell] einfache Dinge ausprobieren könnt. 

## Was ist an R so toll?

Nicht alles an R ist toll — und sobald ihr das erste Mal mehrere Stunden damit verbracht habt, ein vergleichsweise einfaches Problem lösen zu wollen, werdet ihr wissen was ich meine.  

Die am häufigsten zitierten Vorteile sind in etwa die Folgenden:

- **Kostenlos**
    - Keine Lizenzgebühren
    - Keine Update-Gebühren
- **Open Source**
    - Software-Sprech für "jeder kann sich die Innereien angucken"
    - Jeder kann R beliebig erweitern und modifizieren
    - "Was genau macht R an Stelle XYZ" ist immer beantwortbar, weil der Quelltext [offen verfügbar ist](https://github.com/wch/r-source)
- **Erweiterbarkeit**
    - Es gibt unzählige Erweiterungen (*"packages"*) für R, die neue Funktionen bereitstellen
    - Übersicht auf z.B. [r-pkg.org](https://www.r-pkg.org/) 
    - Sogar eure TutorInnen können packages schreiben. Tun sie [sogar manchmal](https://github.com/tadaadata/tadaatoolbox).
- **Gute Dokumentation**
    - R bringt seine Hilfe selber mit, das ist der *"Help"*-Tab in RStudio. Jede Funktion ist dokumentiert!
    - Seiten wie [rdocumentation.org](https://www.rdocumentation.org/) oder [rdrr.io](https://rdrr.io/) erlauben es so gut wie alle verfügbaren R packages nach bestimmten Funktionen zu durchsuchen, egal wie obskur der Anwendungsfall auch sein mag
    - Communities wie [stackoverflow](https://stackoverflow.com/questions/tagged/r) sind beliebte "Ich brauche Hilfe bei XY"-Anlaufstellen, und eine Horde von Menschen, die meistens das gleiche Problem auch schonmal hatten, können euch helfen
- **Interaktivität**: Wo SPSS auf Buttons und Befehle reagiert und dann einen Stapel PDFs produziert, kann R mit der Konsole auch einfach schnell und interaktiv benutzt werden: "Schnell mal eben was nachgucken" ist in R deutlich angenehmer als in SPSS
- **Reproduzierbarkeit**: Wenn ihr ein sauberes R-Script geschrieben habt, könnt ihr das frei verfügbar machen und alle Interessierten können es bei sich selbst ausführen und *BÄM!*, Ergebnisse reproduziert. In case you didn't realize, but that's kind of a big thing in science.
- **Visualisierung**: R hat fantastische Werkzeuge zur Datenvisualisierung, primär sei hier *ggplot2* erwähnt, was euch erlaubt wunderschöne Grafiken aus euren Daten zu zaubern, und auch das vollkommen reproduzierbar (versucht das mal mit SPSS oder Excel. Wolds of pain.)
- **Flexibilität**: R ist eine Programmiersprache, das heißt per default kann R erstmal *alles*. Vielleicht nicht alles gut, aber prinzipiell lässt sich zumindest theoretisch alles damit anstellen. Dieses Dokument hier? In R (RMarkdown, *bookdown*) geschrieben. Dynamische Webseiten? Auch möglich, googlet "R shiny". Interaktive Elemente? Auch kein Ding, googlet "R htmlwidgets". Daten aus Software wie SPSS, Excel oder sogar Google Sheets importieren? Auch kein Problem. You get the idea.
- **Aktive Entwicklung & Community**: R wird *immer besser*. Immer mehr Leute benutzen R, von diesen Leuten haben einige gute Ideen, und davon wiederum gibt es einige, die diese sogar umsetzen. Das Resultat ist ein stetig wachsendes und gedeihendes Ökosystem um R und eine aktive Community auf diversen Netzwerken, die sowohl Hilfestellung liefern können als auch aktiv an besseren Tools rund um R arbeiten, von besserer Dokumentation bis zu besserer Integration mit anderer Software.

## Was ist R **nicht**?

R ist nicht wie SPSS. R "nackt" ist ein Kommandozeilenprogramm. Terminal/Konsole, wie man es auch nennen mag, aber es ist nicht wie die Programme, die ihr im Alltag benutzt. Es gibt keine Knöpfe zum drücken und alles ist Text, ohne Formatierungskram wie **fett** oder *kursiv*, weil die Grundlagen bzw. Vorstufen von R aus einer Zeit kommen, in der Computer noch *anders* waren und die Mauer noch frisch war. 

Weil das wenig benutzerfreundlich bzw. einsteigerfreundlich ist, gibt es Programme wie **RStudio**, was sozusagen auf R sitzt und es benutzbar macht. Wenn R ein Pferd ist, ist RStudio ein Sattel.  
Das heißt für euch aber auch, dass ihr eine Datenanalyse nicht durch bloßes Knöpfchendrücken zusammenstecken könnt wie das bei SPSS möglich ist — ihr müsst Befehle lernen, eure Daten(struktur) verstehen, und euch sicher sein, was ihr tun wollt.  
Ich weiß, dass das alles wirklich eher krampfig klingt wenn ihr das so lest, weshalb es auch häufig vorkommt, dass Studierende in den ersten Semestern R eher ignorieren und sich lieber mit SPSS beschäftigen, weil das weniger kognitiver Aufwand ist — aber glaubt mir wenn ich euch sage, dass "R lernen" eine gute Investition ist. SPSS könnt ihr euch immer noch irgendwie beibringen oder Youtube-Tutorials gucken oder Befehlslisten ausdrucken und sowieso und überhaupt, R hingegen ist entsprechend komplexer, also nutzt die Zeit in der euch TutorInnen noch helfen können, bevor ihr dann vor eurem Expra-Datensatz sitzt, mit SPSS nicht weiter kommt und wie der Ochs vor'm Berg an R sitzt.  

Ich betone das übrigens nicht, weil ich SPSS doof finde (was ich tue), oder R so toll finde (was ich tue), sondern tatsächlich aus Erfahrung und Überzeugung.  
Wenn euch Statistik egal ist und ihr einfach nur bestehen wollt, dann reicht euch vielleicht SPSS. Wenn ihr langfristig gut mit Methodik und quantitativen Methoden arbeiten können wollt, dann ist R eine gute Investition.

<!-- Fußnoten -->
[^schnell]: Das mit der Schnelligkeit kommt mit etwas Übung. Wirklich.
