# (PART) Statistik {-}

# Deskriptive Statistik

In diesem Abschnitt widmen wir uns univariaten und bivariaten *deskriptiven Statistiken*, vom Mittelwert und Standardabweichung über $\chi^2$, *Somers' d* und Korrelationskoeffizienten.  
Wir halten uns (so grob) an die Struktur aus QM1 und QM2, das heißt: Wir kümmern uns beispielsweise zuerst um $\chi^2$ als deskriptive Statistik um dann auf *Cramer's V* zu sprechen zu kommen, und widmen uns erst im folgenden Kapitel dem $\chi^2$-Test als inferenzstatistisches Werkzeug.

## Univariate Statistiken

*Univariat* ist *fancy sprech* für "nur eine Variable", das heißt es geht erstmal noch nicht um Zusammenhänge irgendeiner Art, sondern primär darum wie ein Merkmal **verteilt** ist.  
Die dazugehörigen Kennwerte und Formeln sind sozusagen das kleine 1x1 der Statistik, dementsprechend sind sie auch in R schnell und einfach erreichbar.  
Als Beispieldatensatz nehmen wir mal den *Game of Thrones Deaths*-Datensatz und den `participation`-Datensatz zur Tutorienteilnahme, beide aus dem Kapitel [[Datenimport]]

```{r Ch11_Daten_einlesen}
participation <- readRDS("data/participation.rds")
gotdeaths     <- readr::read_csv("data/got_deaths.csv")
```

### Mittelwert, Median, Modus

### Variabilität und Co

