---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Statistische Tests

## Tests auf Voraussetzungen

### Tests auf Normalvertielung

```{r shapiro}
shapiro.test(qmsurvey$partnerinnen)
```

```{r normtests, warning=FALSE}
library(nortest)

# Anderson-Darling
ad.test(qmsurvey$partnerinnen)
# Shapiro-Francia
sf.test(qmsurvey$partnerinnen)
# Pearson's Chi^2-Anpassungstest
pearson.test(qmsurvey$partnerinnen)
# Kolmogorov-Smirnoff
ks.test(scale(qmsurvey$partnerinnen), y = pnorm)
```


### Tests auf Varianzhomogenität

```{r levene_1}
library(car)

leveneTest(partnerinnen ~ ons, data = qmsurvey)
```

```{r leven_2}
library(tadaatoolbox)

tadaa_levene(qmsurvey, partnerinnen ~ ons, print = "markdown")
```


## $\chi^2$

```{r chisq_xtab}
library(sjPlot)

sjt.xtab(qmsurvey$ons, qmsurvey$ernaehrung,
         show.exp = TRUE, show.legend = TRUE, show.cell.prc = TRUE)
```

```{r chisq_base_r}
chisq.test(qmsurvey$ons, qmsurvey$ernaehrung)
```


```{r chisq_test}
library(tadaatoolbox)

tadaa_chisq(qmsurvey, ons, ernaehrung, print = "markdown")
```

## z- und t-Test

### Eine Stichprobe

```{r z-Test}
tadaa_one_sample(qmsurvey, x = alter, mu = 20, sigma = 3, print = "markdown")
```

```{r t-test_onesample}
tadaa_one_sample(qmsurvey, x = alter, mu = 20, print = "markdown")
```

### Zwei Stichproben

```{r t-test_twosample}
t.test(partnerinnen ~ ons, data = qmsurvey)
```

```{r t-test_twosample_tadaa}
tadaa_t.test(qmsurvey, response = partnerinnen, group = ons, paired = FALSE, print = "markdown")
```

## Varianzanalyse (ANOVA)

### Einfaktorielle ANOVA

### Mehrfaktorielle ANOVA

### ANOVA mit Messwiederholung (rmANOVA)

## Regression

### Einfache Lineare Regression

### Multiple Regression

### Logistische Regression
