project:
  type: book

book:
  title: "R für Psychos"
  author: "Tobi & Lukas"
  date: today
  date-format: medium
  chapters:
    - index.qmd
    - part: "Vorbereitung"
      chapters:
        - chapters/01-Was-ist-R.qmd
        - chapters/02-Installation.qmd
        - chapters/03-Orientierung.qmd
    - part: "Grundlagen"
      chapters:
        - chapters/04-Erste-Schritte.qmd
    - references.qmd
  appendices:
    - chapters/A01-Ressourcen.qmd

bibliography: references.bib

format:
  html:
    theme: spacelab # quartz
    lang: de_DE
    code-fold: show
    code-copy: true
    code-link: true
  pdf:
    documentclass: scrreprt
from: markdown+emoji
knitr:
  opts_chunk:
    collapse: true
    comment: "#>"
execute:
  freeze: auto
  cache: true
