project:
  type: book

from: markdown+emoji
lang: de
date: last-modified
date-format: long
author:
  - name: "Lukas Burk"
  - name: "Tobias Anton"

book:
  title: "R für Psychos"
  open-graph: true
  page-footer: "CC-BY-NC Lukas Burk & Tobias Anton"
  repo-url: "https://github.com/tadaadata/r-intro-book"
  chapters:
    - index.qmd
    - part: "Vorbereitung"
      chapters:
        - chapters/01-was-ist-r.qmd
        - chapters/02-installation.qmd
        - chapters/03-orientierung.qmd
    - part: "Grundlagen"
      chapters:
        - chapters/04-erste-schritte.qmd
        - chapters/05-datentypen.qmd
        - chapters/06-packages.qmd
        - chapters/07-die-hilfe.qmd
        - chapters/08-datenimport.qmd
    - part: "Der Spaßige Teil"
      chapters:
        #- chapters/09-visualisierung.qmd
        - chapters/10-berichte.qmd
    #- references.qmd
  appendices:
    - chapters/a01-ressourcen.qmd
    - chapters/a02-glossar.qmd
    - chapters/a99-reproduzierbarkeit.qmd

bibliography: references.bib

format:
  html:
    theme: spacelab # quartz
    code-fold: show
    code-copy: true
    code-link: true
    code-summary: "Code verbergen/anzeigen"
    title-block-banner: true
    title-block-style: default
    fig-align: center
    fig-responsive: true
  # pdf:
  #   documentclass: scrreprt
knitr:
  opts_chunk:
    collapse: true
    comment: "#>"
execute:
#  freeze: auto
  cache: true
