---
title: "R für Psychos"
author: "Lukas Burk & Tobias Anton"
date: "Stand: `r format(Sys.time(), '%d. %B %Y @ %H:%M Uhr')`"
lang: de-DE
publisher: r-intro.tadaa-data.de
rights: "Copyright 2017, Lukas Burk & Tobias Anton, CC-BY-NC"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: 'tadaa-data/r-intro-book'
url: 'https\://r-intro.tadaa-data.de/book/'
description: "Eine Einführung in R für Menschen ohne Vorkenntnisse"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = "")
```

# Vorwort {-}

Das hier wird gerade eine R-Einführung für Psychologiestudierende so mit ganz ohne Vorwissen im Bereich Software oder Programmierung.

Die grobe Idee ist es, eine Präsentaion für die Übung zu haben, und zusätzlich eine long-form Intro als Nachschlagwerk und vertiefendes Intro.  
Beides sollte ausreichend mit Screenshots/Beispielen ausgefüttert sein um auch die verunsichertesten Neulinge bei der Stange zu halten.

## Für TutorInnen und Leute mit zu viel Motivation {-}

Wenn ihr noch keine Ahnung habt wie R funktioniert, wie man einen Computer bedient oder was Versionskontrollsysteme sein sollen, dann könnt ihr das hier überspringen. Wenn ihr aber Ergänzungen oder Korrekturen machen wollt, dann ist das auch möglich!

Um an diesem Projekt mitzuarbeiten könnt ihr entweder den *edit* (<i class="fa fa-edit fa-lg"></i>) button auf der Web-Version oben in der Leiste klicken, oder direkt auf das [GitHub repository](https://github.com/tadaadata/r-intro-book) gehen und dort entweder Issues erstellen oder direkt Pull Requests machen.

## Über diese Einführung {-}

Tobi und Lukas haben zwei Jahre lang die R-Einführung in QM gehalten, basierend auf den Folien, die Lukas unter Anderem auch als Nachschlagwerk gedacht hatte.  
Weil Lukas aber ein gigantischer Nerd mit viel zu viel Spaß an Programmierzeugs ist, und sich sonst niemand für technische Details interessiert, brauchte er die Hilfe von Tobi und einer Hand voll TutorInnen um die Einführung menschenkompatibel zu halten.  
Das Resultat ist/wird zum Einen diese Website/Buch/Dings, und zum Anderen die [Folien der Übung](https://r-intro.tadaa-data.de/slides/).  

Diese Einführung hier wird deutlich stärker ins Detail gehen, und soll auf kurz oder lang so ziemlich alles abdecken, was ihr in zwei Semestern *Quantitative Methode* brauchen werdet.  
Okay, ihr werdet das Ganze auch in *Methodenlehre* brauchen.  
Und in *Diffenzielle*.  
Und im Expra.  
Und vermutlich danach auch. 

Wenn ihr mehr (oder so grob dasselbe, aber in besser erklärt) wollt, dann empfehle ich herzlichst "[**R for Data Science**](http://r4ds.had.co.nz/)", ein kostenloses Buch von Hadley Wickham, einem der populärsten R-Menschen^[Populär, weil er einfach unheimlich viel raushaut. Packages, Vorträge, Bücher, alles. All hail Hadley!].

## Verfügbarkeit {-}

Wenn ihr das hier als Website unter `https://r-intro.tadaa-data.de/book` lest, dann habt ihr schonmal alles richtig gemacht. Zusätzlich gibt es diese Website auch als Ebook (`.epub`, funktioniert auf allen gängigen e-readern, tablets, smartphones und sowieso) unter dem Downloadbutton in der obigen Leiste.  
Zusätzlich gibt es die Ebook-Version auch als PDF, wobei es sein kann, dass Teile der Formatierung nicht ganz sauber konvertiert werden, was insbesondere bei mathematischen Ausdrücken vorkommen kann.  
Die Website (also HTML) ist allerdings das *primäre* Format dieser Einführung, der einzige Nachteil ist, dass sich die Website schlecht ausdrucken lässt — aber wenn ihr Websites ausdruckt habt ihr sowieso die Kontrolle über euer Leben verloren.  
Wenn ihr diese Einführung unbedingt offline verfügbar und portabel haben wollt, bleibt euch die PDF- oder Ebook-Version. Und wehe ihr druckt die aus. Wehe.

Anbei: Auf der Web-Version haben wir analytics Zeug eingebunden, was uns sagt, welche Kapitel am häufigsten besucht werden. Die Idee dahinter ist relativ simpel: Wenn ein Kapitel besonders häufig besucht wurde, ist es vermutlich interessant, ergo ist es vermutlich auch sinnvoll, da mehr Aufwand reinzustecken als in andere.  
Wenn ihr AdBlock und Kram installiert habt, wäre es entsprechend hilfreich für uns, das auf dieser Seite zu deaktivieren. Werbung haben wir hier eh nicht, und die Tracking-Daten landen auch nur bei uns und nicht bei Google, Facebook oder der Stasi.

## Zielgruppe {-}

Die primäre Motivation und Zielgruppe für diese Einführung sind die Studierenden der Psychologie an der Universität Bremen, weshalb hier auch möglichst wenig Vorkenntnisse im Bereich der Statistik, Programmierung, statistischen Programmierung oder programmierenden Sta… ähm… ihr versteht schon.  
Wir gehen anfangs sehr kleinschrittig vor und versuchen gängige Konzepte wie Datentypen/-klassen, Datenstrukturen, Syntax von Grund auf zu erklären.  

Solltet ihr bei Begriffen wie "funktionale Programmiersprache", "generics", "functionals" und "Attribute" ein grobes Bild im Kopf haben, dann empfehle ich euch einen Blick in das weiter oben erwähnte [**R for Data Science**](http://r4ds.had.co.nz/). Also generell würde ich allen interessierten dieses Buch/Seite empfehlen, aber ich vermute, dass es für einen absoluten Sprung ins kalte Wasser R nur dann geeignet ist, wenn man entweder sehr viel Motivation oder ein entsprechendes Vorwissen mitbringt.
