# Glossar

Für diejenigen, die in Mathe immer ein bisschen verwirrt waren, sobald Symbole benutzt wurden:  
Hier ein bisschen Vokabular.

## Griechische Buchstaben

Das hier ist kein vollständiges griechisches Alphabet (das könnt ihr gefällist [selber googlen](https://de.wikipedia.org/wiki/Griechisches_Alphabet)), sondern nur ein kleiner Auszug der griechischen Buchstaben, die euch in QM so begegnen können.

Buchstabe | Sprich       | Benutzung
----------|--------------|---------------------------------------------
$\alpha$           | "Alpha"         | Fehler 1. Art
$\beta$            | "Beta"          | Fehler 2. Art
$\gamma$           | "Gamma"         | Statistik / Effektgröße
$\delta$, $\Delta$ | "Delta" (kleines, großes) | Effektgröße, allgemein "Unterschied", "Differenz"
$\eta$             | "Eta"           | Statistik / Effektgröße
$\lambda$          | "Lambda"        | Statistik / Effektgröße
$\mu$              | "Mü"            | Populationsmittelwert; Parameter
$\pi$              | "Pi"            | Das mit dem Kreis halt. Wisstschon.
$\rho$             | "Rho"           | Statistik / Effektgröße; Alternative zu Pearson's $r$
$\sigma$, $\Sigma$ | "Sigma" (kleines, großes) | Standardabweichung in der Population bzw. Summenzeichen ($\sum^n_{i = 1}$)
$\phi$             | "Phi"           | Statistik / Effektgröße (QM1)
$\chi$             | "Chi" (meistens "tschi") | (Test-)Statistik (QM1, QM2)
$\omega$, $\Omega$ | Omega (kleines, großes)  | Effektgröße (QM2)

## "Was für eine Taste?" {#tasten}

### Tasten

Wikipedia hat [da was für euch](https://de.wikipedia.org/wiki/Tastaturbelegung#Beschreibung_der_Tasten).

- [*Control* (deutsch: *Steuerung*), Strg, ctrl](https://duckduckgo.com/?q=strg+taste&t=hg&iax=images&ia=images)
- [*Command* (auf Macs)](https://duckduckgo.com/?q=command+key+mac&t=hg&iax=images&ia=images)
- [*Shift*](https://duckduckgo.com/?q=shift+taste+auf+tastatur&t=hg&iar=images&iax=images&ia=images)
- [*Tab*](https://duckduckgo.com/?q=tab+taste&t=hg&iar=images&iax=images&ia=images)
- [*Alt*](https://duckduckgo.com/?q=alt+taste&t=hg&iar=images&iax=images&ia=images)
- [*Alt Gr* (nicht auf Macs)](https://duckduckgo.com/?q=alt+gr+key&t=hg&iax=images&ia=images)
- [*Enter*](https://duckduckgo.com/?q=entertaste&t=hg&iar=images&iax=images&ia=images)
- [*Backspace*](https://duckduckgo.com/?q=backspace+key&t=hg&iar=images&iax=images&ia=images)

### Zeichen

Wenn wir von bestimmten Zeichen reden, ist es gut, wenn ihr wisst wovon wir reden.  
Die Zeichen findet ihr alle auf eurer Tastatur. Wenn ihr nicht wisst wie ihr sie eingebt, dann googlet ihr "Wie gebe ich XYZ ein". Die Mac-UserInnen hängen noch "auf Mac" an die Suchanfrage.  

- Klammern:
    - `( )`: Runde Klammern / Parentheses / Round Parentheses
    - `{ }`: Geschweifte Klammern / Curly Braces
    - `[ ]`: Eckige Klammern / Brackets 
    - `< >`: Spitze Klammern / auch "größer" bzw. "kleiner" Zeichen
    
- Anführungszeichen:
    - `` ` ` ``: Backticks, Akzent
    - `" "`: Doppelte Anführungszeichen / Double Quotes
    - `' '`: Einfache Anführungszeichen / Single Quotes / Meistens als Apostroph benutzt

- Rechenzeichen
    - `+`: Plus
    - `-`: Minus, Bindestrich. Kein Unterstrich. Bindestrich.
    - `/`: Geteilt durch, *Slash*
    - `^`: Circumflex, e.g. `x^2`

- Logische Operatoren
    - `==`: Doppeltes `=` Zeichen **Ohne Leerzeichen dazwischen**
    - `!=`: Nicht gleich, Ausrufezeichen und Gleicheitszeichen **Ohne Leerzeichen dazwischen**
    - `|`: Gerader Strich, auch "Pipe"
    - `>`: Größer als
    - `<`: Kleiner als
    - `>=`: Größer gleich **Ohne Leerzeichen dazwischen**
    - `<=`: Kleiner gleich **Ohne Leerzeichen dazwischen**
    
- Andere Zeichen:
    - `!`: Ausrufezeichen
    - `$`: Dollar-Zeichen. **Nicht §**. Das ist was anderes. 
    - `/`: Slash, "Geteilt durch"
    - `\`: Backslash. Gegenstück zu `/`. Teilt *nicht*.
    - `-`: Bindestrich, Minus
    - `#`: Für Kommentare. Raute, Lattenzaun, [Octothorpe](https://en.wikipedia.org/wiki/Number_sign#Other_names_in_English). Nein, kein Hashtag.


## Übersicht: Grundfunktionen

In _**all**_ den Kapiteln werden ein großer Haufen Funktionen bereits vorgestellt, genutzt und erklärt. Eine kurze Übersicht ist dennoch, oder daher, bestimmt nicht verkehrt.

### Statistiken

Für einen kurzen Blick auf die Daten:

Funktionsname | macht:                | Beispiel
:-------------|:----------------------|:--------------------------
`mean()`      | Mittelwert berechnen  | `mean(qm$alter, na.rm = T)`
`median()`    | Median berechnen      | `median(qm$alter, na.rm = T)`
`sd()`        | Standardabweichung    | `sd(qm$alter, na.rm = T)`
`var()`       | Varianz               | `var(qm$alter, na.rm = T)`
`quantile()`  | Quantile (default: 4) | `quantile(qm$alkohol, type = 3)`
`table()`     | einfache Häufigkeits- oder Kontingenztabelle  | `table(qm$gender, qm$ons)`
`summary()`   | einfache Übersicht eines Objekts              | `summary(qm)`, `summary(qm$alter)`

### Zahlenreihen

Manchmal braucht man einfach 100x abwechselnd 1 und 2, eine einfache Durchnummerierung oder eine Hand voll normal-/t-/$\chi^2$/etc.-verteilter Zufallszahlen.

Funktionsname | macht:                            | Beispiel
:-------------|:----------------------------------|:----------------
`a:b`         | Sequenz von a bis b               | `1:10`  
`seq()`       | gibt eine beliebige Sequenz aus   | `seq(from = 10, to = 91, by = 9)`
`seq_len()`   | zählt von 1 bis _Argument_        | `seq_len(20)`
`seq_along()` | wie `seq_len()`, nur entlang eines Vektors    | `seq_along(qm$gender)`
`rep()`       | wiederholt etwas (nicht nur Zahlen!) _n_ mal  | `rep(c(2, 4), times = 5)`
...           | `times` sagt, wie oft **das Ganze**           | `rep(c("fuck", "yeah"), times = 5)`
...           | `each` sagt, wie oft **jedes Einzelne**       | `rep(c("fuck", "yeah"), each = 3)`
`rnorm()`     | erstellt _n_ normalverteilte Zufallszahlen    | `rnorm(n = 30, mean = 100, sd = 15)`
`rt()`        | erstellt _n_ t-verteilte...                   | `rt(n = 30, df = 12)`
`rchisq()`    | $\chi^2$-verteilte...                         |
`rbeta()`     | beta-verteilte...                             |
`rpois()`     | poisson-verteilte...                          |
...           | $\rightarrow$ siehe `?Distributions`          |

### Arithmetik ("rechnen")

Und manchmal möchte man einfach nur ein bisschen was ausrechnen.

Funktionsname | macht:                                      | Beispiel
:-------------|:--------------------------------------------|:-----------------------
`sum()`       | Summe bilden                                | `sum(qmsurvey$arbeit)`
`cumsum()`    | Kumulierte Häufigkeiten bilden              | `cumsum(qmsurvey$arbeit)`
`diff()`      | Differenzen bilden                          | `diff(qmsurvey$arbeit)`
